baseurl = "https://serene-nightingale-d0b077.netlify.app"
metaDataFormat = "yaml"
title = "Travel Photo Blog"
theme = "blist"

DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    contentDir = "content/en" #English
    weight = 2
    languageName = "English"
    [languages.en.params]
      introTitle = "Hey, how you doing"
      introSubtitle = "Two people eager to travel, a van and a dog."
      introPhoto = "/images/site/feature_picture.jpeg"
    [[languages.en.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 1

    [[languages.en.menu.main]]
        name = "About us"
        url = "page/about/"
        weight = 2

    [[languages.en.menu.main]]
        name = "Tags"
        url = "tags"
        weight = 3

  [languages.de]
    contentDir = "content/de" # Deutsch
    weight = 1
    languageName = "Deutsch"
    title = "Travel Photo Blog"
    description = "Reisen und Stellplätze für Vans und andere Gefährte"
    [languages.de.params]
      introTitle = "Hey, how you doing"
      introSubtitle = "Zwei reiselustige Leute, ein Van und ein Hund."
      introPhoto = "/images/site/feature_picture.jpeg"
    [[languages.de.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 1

    [[languages.de.menu.main]]
        name = "Über uns"
        url = "page/about/"
        weight = 2

    [[languages.de.menu.main]]
        name = "Tags"
        url = "tags"
        weight = 3

[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = true

  # Custom copyright - optional
  copyright = "Copyright © 2022 - Jannis Wienert aka cptnuggetplus · All rights reserved"
  favicon = "/favicon.svg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-indigo-100"

[params.homepage.social]
  # Global params xommon for both languages
  title = "Follow us"
  description = "Check out stuff in this platforms as well"
  twitter = "https://twitter.com/"
  #linkedin = "https://linkedin.com/in/"
  #xing = "https://www.xing.com/profile/"
  #github = "https://github.com/"
  #medium = "https://medium.com/"
  #reddit = "https://reddit.com/"
  #dribbble = "https://dribbble.com/"

[[menu.main]]
  name = "About"
  url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
